### ISSUE TITLE
Allow for creation of runs on all databases at once

### ISSUE THREAD

**Issue by paulholden** [moodlehq/moodle-local_ci#261]
Similar to the `list_of_mdls` criteria, but for creation of jobs across all four databases we support

Allow to restrict by suite/tag/name, as was recently implemented in the above

But with certain restrictions so as to not DOS our CI runners: single branch only; either PHPUnit **or** Behat; more..?

@stronk7 can probably give better context than me!

**Comment by stronk7** [comment]
Just pasting here what I have in my notes:

Add a new criteria that allows you to select between:
- phunit or behat
- one branch (maybe we can default to master to start with, I'm worried about allowing multiple and available slots in infra).
- 1-n databases (comma separated list of dbtypes)
- Keeping all the rest of possible configurations that the current list-of-mdl issues have, namely:
    - browser (headless...)
    - tags
    - filter
    - name
    - ...

And a job to ci.moodle.org/Tracker to configure and launch it.

**Comment by stronk7** [comment]
The first implementation of the new criteria (still not deployed @ CIs, it's running locally only) seems to be working acceptably well. You can select the job type, the target databases and the filter/testsuite/tags/name.

![multi-database-tests](https://user-images.githubusercontent.com/167147/233209184-855bfc14-3988-4f97-8b41-abb18202833b.png)

Tomorrow I'll perform a few more tests and then will enable the new [multi-database job](https://ci.moodle.org/view/Tracker/job/TR%20-%20Bulk%20pre-launch%20DEV%20jobs%20(multi_database)/) that will run it @ CIs.

Ciao :-)

**Comment by stronk7** [comment]
Ok, I'm closing this as done:

- The code is @ https://github.com/moodlehq/moodle-local_ci/commit/901cbaa9b24a64844f2a6c1e541736139fe905fc
- The job is @ https://ci.moodle.org/view/Tracker/job/TR%20-%20Bulk%20pre-launch%20DEV%20jobs%20(multi_database)/

Feel free to report any problem or suggestion, ciao :-)
