### ISSUE TITLE
Validating mustache templates that use string helpers for URLs causes warnings

### ISSUE THREAD

**Issue by smeikx** [moodlehq/moodle-local_ci#270]
We use language strings in a certain way to improve accessibility:

```mustache
<a href='{{#str}} localised_url, local_plugin {{#str}}'>some external page</a>
```

The localised URL is usually something like `example.org/?lang=de` or `example.com/en`.

Unfortunately, [`moodle-local_ci/mustache_lint/mustache_lint.php`](https://github.com/moodlehq/moodle-local_ci/blob/4bc8230ff53b341cf3fa14ac5fd2ae37d274ee57/mustache_lint/mustache_lint.php#L90) wraps the helper’s parameters in brackets (`[[ localised_url, local_plugin ]]`) which causes warnings when validating the HTML, because brackets are not allowed in a URL.

Could we maybe just `urlencode()` the string instead of wrapping it in brackets?  
What was the reasoning behind using brackets in the first place?  
Maybe there is an even better way of solving this?

**Comment by stronk7** [comment]
Thanks @smeikx .

I certainly cannot imagine any reason for those square brackets to be a must so, in #272, I've proceeded to replace them with (allowed) parenthesis and also, url-encoding the helper contents, so they are url/href safe.

Let's see if that passes all our tests... ciao 🙂
