### ISSUE TITLE
Composer installs local_ci recursively in infinite loop?

### ISSUE THREAD

**Issue by justusdieckmann** [moodlehq/moodle-local_ci#280]
In our CI, `composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4` fails after trying to install the dependencies over and over again: https://github.com/learnweb/moodle-local_sap/actions/runs/6052916003/job/16427309095

The command ends with
```
Failed to set PHP CodeSniffer installed_paths Config
Script @composer update --prefer-dist --optimize-autoloader --working-dir=vendor/moodlehq/moodle-local_ci handling the local-ci-install event returned with error code 127
Script @local-ci-install was called via post-update-cmd
Script @composer update --prefer-dist --optimize-autoloader --working-dir=vendor/moodlehq/moodle-local_ci handling the local-ci-install event returned with error code 127
(...)
Script @composer update --prefer-dist --optimize-autoloader --working-dir=vendor/moodlehq/moodle-local_ci handling the local-ci-install event returned with error code 127
Script @local-ci-install was called via post-update-cmd
Script @composer update --prefer-dist --optimize-autoloader --working-dir=vendor/moodlehq/moodle-local_ci handling the local-ci-install event returned with error code 127
Script @local-ci-install was called via post-install-cmd
Error: Process completed with exit code 127.
```

It seems like a recursive loop related to local_ci, which is why I am putting this issue here. Do you have any idea what the problem might be?

**Comment by justusdieckmann** [comment]
Ok, I have now seen that the the post-install / post-update-cmds are defined in moodlehq/moodle-plugin-ci. But since this is the only obvious change, could this somehow be caused by setting the name in the composer.json in ba35d05 @stronk7?

Cheers
Justus

**Comment by stronk7** [comment]
Hi @justusdieckmann ,

thanks for reporting this.

Yeah, we detected the problem yesterday and current situation is:

1. It's a change of behaviour that has happened with Composer 2.6.0 (and 2.6.1), released yesterday (Sept 1st 2023). Such a change has been reported @ https://github.com/composer/composer/issues/11613
2. Version 2.5.8 of Composer is working ok so, as quick workaround, you always can force it in your workflows, (setup-php action) by specifying `tools: composer:2.5.8`.
3. They way we are incorporating `moodle-local_ci` dependencies into `moodle-plugin-ci` is quite old, coming from the times where local_ci did not have its own composer.json files. We are working to fix that. And that change will make us immune to the Composer 2.6.x new behaviour (irrespectively if it's fixed or no).
4. A new `moodle-plugin-ci` version is planned to happen as soon as we have everything tested with it. Once that happens, automatically all new builds (Travis and GHA) will come back to green.

And that's the plan, so far. I'll keep this issue updated.

Ciao :-)

**Comment by stronk7** [comment]
> …
> But since this is the only obvious change, could this somehow be caused by setting the name in the composer.json in [ba35d05](https://github.com/moodlehq/moodle-local_ci/commit/ba35d05f8068075035dc05f3e9bde0f0a6228fa9) @stronk7?
> …
Heh, no, no. In fact that commit (and 1.0.20 release) that we did yesterday… was done after detecting the problem. And it’s part of the solution, to allow us to install local_ci packages in a better way.

**Comment by stronk7** [comment]
Update: `moodle-local_ci` v1.0.21 has been just released and it includes all the changes required to allow it to work perfectly when installed as a dependency (while continuing working standalone).

Next step: Make `moodle-plugin-ci` to start using the just released `moodle-local_ci` version, removing the old stuff that was used previously to install it (post-x commands). This should workaround the Composer >= 2.6.0 problems with a good fix (better use of normal dependencies).

Ciao :-)

**Comment by stronk7** [comment]
Update: This [is the commit](https://github.com/stronk7/moodle-plugin-ci/commit/66728d320b54d20c9651b71ddaeaf54aaf3d63e4) of `moodle-plugin-ci` that should make the magic. It changes the way `moodle-local_ci` dependencies are installed (from the ancient one to a more correct one).

Next step: Verify that the solution above works both for `moodle-plugin-ci` v3 and v4. Locally and against some real plugin. Then, if everything goes ok, will make the corresponding releases that, automatically, should fix all the current failures happening everywhere.

**Comment by stronk7** [comment]
Update: All the tests ended ok.
- `moodle-plugin-ci` v4 own tests are passing 100% ([link](https://github.com/stronk7/moodle-plugin-ci/actions/runs/6059324003)).
- `moodle-plugin-ci` v3 own tests are passing 100% ([link](https://github.com/stronk7/moodle-plugin-ci/actions/runs/6059427833)).
- `moodle-local_codechecker`(a real plugin that was failing with the recursion problem) is now passing, both with v3 and v4 changes applied ([link](https://github.com/stronk7/moodle-local_codechecker/actions/runs/6059436825)).

Next step: Prepare the v3 and v4 releases. Then, party!

**Comment by stronk7** [comment]
Update: `moodle-plugin-ci`[3.4.13](https://github.com/moodlehq/moodle-plugin-ci/releases/tag/3.4.13) has been released.

**Comment by stronk7** [comment]
Update: `moodle-plugin-ci` [4.1.2](https://github.com/moodlehq/moodle-plugin-ci/releases/tag/3.4.13) has been released.

**Comment by stronk7** [comment]
And that's all!

Now, new runs of `moodle-plugin-ci` in Travis or GHA should be back to pass everywhere, yay!

Test run (that includes both v3 and v4 branches): https://github.com/stronk7/moodle-local_codechecker/actions/runs/6059737448

I will leave this open a few time, to see if there is any remaining problem and/or getting confirmation that everything is back to work normally.

Ciao :-)

**Comment by justusdieckmann** [comment]
Thank you very very much for the information and especially your quick work!

**Comment by stronk7** [comment]
Also, for the records, Composer 2.6.2 has been released and includes a fix for the problem (no matter we are already immune to it). That should be enough to help people having moodle-plugin-ci forks / non-updated environments...

https://github.com/composer/composer/releases/tag/2.6.2

Closing this now, ciao :-)
